project:
  name: cfn-abi-crowdstrike-fcs
  owner: support@crowdstrike.com # to be updated
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  eks-only-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      DeploymentScope: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EKSProtection: "true"
      FalconCID: $[taskcat_ssm_/crowdstrike/falcon_cod]
      DockerAPIToken: $[taskcat_ssm_/crowdstrike/falcon_docker_api_token]
      ECRConnections: "false"
      EnableSSMDistributor: "false"
      EKSRegions: $[taskcat_current_region]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml

  ecr-only-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      DeploymentScope: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      ECRConnections: "true"
      EKSProtection: "false"
      EnableSSMDistributor: "false"
      ECRRegions: $[taskcat_current_region]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml

  ssm-only-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      DeploymentScope: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableSSMDistributor: "true"
      EKSProtection: "false"
      ECRConnections: "false"
      SSMRegions: $[taskcat_current_region]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml

  all-three-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      DeploymentScope: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EKSProtection: "true"
      FalconCID: $[taskcat_ssm_/crowdstrike/falcon_cod]
      DockerAPIToken: $[taskcat_ssm_/crowdstrike/falcon_docker_api_token]
      ECRConnections: "true"
      EnableSSMDistributor: "true"
      EKSRegions: $[taskcat_current_region]
      ECRRegions: $[taskcat_current_region]
      SSMRegions: $[taskcat_current_region]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
