project:
  name: cfn-abi-crowdstrike-fcs
  owner: support@crowdstrike.com # to be updated
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  cw-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-dspm-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableDSPM: "true"
      DSPMRegions: $[taskcat_current_region]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-eks-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      DockerAPIToken: $[taskcat_ssm_/crowdstrike/falcon_docker_api_token]
      FalconCID: $[taskcat_ssm_/crowdstrike/falcon_cod]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-trail:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateIOAOrgTrail: "true"
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-ssm:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableSSMDistributor: "true"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-smlambda:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      APICredentialsStorageMode: "lambda"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-all:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableSSMDistributor: "true"
      CreateIOAOrgTrail: "true"
      CreateSRAOrgTrail: "true"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-sra:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateSRAOrgTrail: "true"
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-sra-nonct:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateSRAOrgTrail: "true"
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      pControlTower: 'false'
      pLogArchiveAccountId: $[taskcat_ssm_/nonct/log-archive-account-id]
      pSecurityAccountId: $[taskcat_ssm_/nonct/audit-account-id]
      pGovernedRegions: 'us-east-1,us-east-2'
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
