apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconAdmission
metadata:
  name: falcon-admission
spec:
  falcon_api:
    client_id: FALCON_CLIENT_ID
    client_secret: FALCON_CLIENT_SECRET
    cloud_region: autodiscover
  registry:
    type: REGISTRY
