---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SecretName:
    SecretsManagerSecretName:
    Description: Secrets Manager Secret Name that contains the Falcon ClientId, ClientSecret, and Cloud for the CrowdStrike APIs.
    Type: String
    Default: 'crowdstrike-falcon-api'
  PermissionsBoundary:
    Type: String
    Description: The name of the policy used to set the permissions boundary for IAM roles.
    Default: ''
  GovCloud:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false

Conditions:
  IsGovCloud: !Equals [ !Ref 'GovCloud', true ]

Resources:
  ECRLambda:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Lambda custom resource only run during stack lifecycle events.
          - id: W92
            reason: Lambda custom resource only run during stack lifecycle events.
      checkov:
        skip:
          - id: CKV_AWS_115
            comment: Lambda does not need reserved concurrent executions.
          - id: CKV_AWS_116
            comment: DLQ not needed, as Lambda function only triggered by CloudFormation events.
          - id: CKV_AWS_117
            comment: Lambda does not need to communicate with VPC resources.
          - id: CKV_AWS_173
            comment: Environment variables are not sensitive.
    Properties:
      Environment:
        Variables:
          secret_name: !Ref SecretsManagerSecretName
          secret_region: !Ref {AWS::Region}
          permissions_boundary: !Ref PermissionsBoundary
          crowdstrike_principal: !If [ IsGovCloud, '', 'arn:aws:iam::292230061137:role/CrowdStrikeCustomerRegistryAssessmentRole']
          gov_cloud: !Ref GovCloud
      Handler: lambda.lambda_handler
      MemorySize: 128
      Role: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${EKSExecutionRoleName}
      Runtime: python3.11
      Timeout: 300
      FunctionName: crowdstrike-abi-eks-events-function
      Code:
        S3Bucket: !Ref StagingS3Bucket
        S3Key: !Sub ${SourceS3BucketNamePrefix}/lambda_functions/packages/eks-new-clusters/lambda.zip